version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./vol/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      TIMEZONE: Europe/London

  wordpress:
    depends_on:
      - db
    user: "1000:1000"
    image: wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./vol/wp:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress


#https://pe.wordpress.org/themes/baskerville/
#https://wpmayor.com/how-to-create-custom-wordpress-document-library/